// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BoothStateCreate = {
    name: string;
    description?: (string | null);
    id: number;
};

export type BoothStateRead = {
    name: string;
    description?: (string | null);
    id: number;
};

export type ClientCreate = {
    name: string;
};

export type ClientRead = {
    name: string;
    id: string;
    created_at: string;
    updated_at: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrgUnitCreate = {
    name: string;
    type?: (string | null);
    timezone?: (string | null);
    client_id: string;
    parent_id?: (string | null);
};

export type OrgUnitRead = {
    name: string;
    type?: (string | null);
    timezone?: (string | null);
    id: string;
    client_id: string;
    parent_id: (string | null);
    created_at: string;
    updated_at: string;
};

export type PhoneBoothCreate = {
    name: string;
    serial_number: string;
    timezone?: (string | null);
    last_seen?: (string | null);
    state_id?: (number | null);
    client_id?: (string | null);
    org_unit_id?: (string | null);
};

export type PhoneBoothRead = {
    name: string;
    serial_number: string;
    timezone?: (string | null);
    last_seen?: (string | null);
    state_id?: (number | null);
    id: string;
    client_id: (string | null);
    org_unit_id: (string | null);
    created_at: string;
    updated_at: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RoleCreate = {
    name: string;
    description?: (string | null);
};

export type RoleRead = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type SensorCreate = {
    type?: (string | null);
    mqtt_topic?: (string | null);
    status?: string;
    phone_booth_id: string;
};

export type SensorEventCreate = {
    state_id: number;
    event_time_utc: string;
    raw_payload?: ({
    [key: string]: unknown;
} | null);
    sensor_id: string;
    phone_booth_id: string;
    client_id: string;
    org_unit_id: string;
};

export type SensorEventRead = {
    state_id: number;
    event_time_utc: string;
    raw_payload?: ({
    [key: string]: unknown;
} | null);
    id: string;
    sensor_id: string;
    phone_booth_id: string;
    client_id: string;
    org_unit_id: string;
    received_at: string;
};

export type SensorRead = {
    type?: (string | null);
    mqtt_topic?: (string | null);
    status?: string;
    id: string;
    phone_booth_id: string;
    created_at: string;
    updated_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UsageSessionCreate = {
    start_time: string;
    end_time?: (string | null);
    duration_seconds?: (number | null);
    phone_booth_id: string;
    client_id: string;
    org_unit_id: string;
};

export type UsageSessionRead = {
    start_time: string;
    end_time?: (string | null);
    duration_seconds?: (number | null);
    id: string;
    phone_booth_id: string;
    client_id: string;
    org_unit_id: string;
    created_at: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type BoothStatesReadBoothStatesResponse = (Array<BoothStateRead>);

export type BoothStatesCreateBoothStateData = {
    requestBody: BoothStateCreate;
};

export type BoothStatesCreateBoothStateResponse = (BoothStateRead);

export type BoothStatesReadBoothStateData = {
    id: number;
};

export type BoothStatesReadBoothStateResponse = (BoothStateRead);

export type BoothStatesUpdateBoothStateData = {
    id: number;
    requestBody: BoothStateCreate;
};

export type BoothStatesUpdateBoothStateResponse = (BoothStateRead);

export type BoothStatesDeleteBoothStateData = {
    id: number;
};

export type BoothStatesDeleteBoothStateResponse = (Message);

export type ClientsReadClientsResponse = (Array<ClientRead>);

export type ClientsCreateClientData = {
    requestBody: ClientCreate;
};

export type ClientsCreateClientResponse = (ClientRead);

export type ClientsReadClientData = {
    id: string;
};

export type ClientsReadClientResponse = (ClientRead);

export type ClientsUpdateClientData = {
    id: string;
    requestBody: ClientCreate;
};

export type ClientsUpdateClientResponse = (ClientRead);

export type ClientsDeleteClientData = {
    id: string;
};

export type ClientsDeleteClientResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OrgUnitsReadOrgUnitsResponse = (Array<OrgUnitRead>);

export type OrgUnitsCreateOrgUnitData = {
    requestBody: OrgUnitCreate;
};

export type OrgUnitsCreateOrgUnitResponse = (OrgUnitRead);

export type OrgUnitsReadOrgUnitData = {
    id: string;
};

export type OrgUnitsReadOrgUnitResponse = (OrgUnitRead);

export type OrgUnitsUpdateOrgUnitData = {
    id: string;
    requestBody: OrgUnitCreate;
};

export type OrgUnitsUpdateOrgUnitResponse = (OrgUnitRead);

export type OrgUnitsDeleteOrgUnitData = {
    id: string;
};

export type OrgUnitsDeleteOrgUnitResponse = (Message);

export type PhoneBoothsReadPhoneBoothsData = {
    clientId?: (string | null);
    limit?: number;
    skip?: number;
};

export type PhoneBoothsReadPhoneBoothsResponse = (Array<PhoneBoothRead>);

export type PhoneBoothsCreatePhoneBoothData = {
    requestBody: PhoneBoothCreate;
};

export type PhoneBoothsCreatePhoneBoothResponse = (PhoneBoothRead);

export type PhoneBoothsReadBusyPhoneBoothsData = {
    clientId?: (string | null);
    limit?: number;
    skip?: number;
};

export type PhoneBoothsReadBusyPhoneBoothsResponse = (Array<PhoneBoothRead>);

export type PhoneBoothsReadPhoneBoothData = {
    id: string;
};

export type PhoneBoothsReadPhoneBoothResponse = (PhoneBoothRead);

export type PhoneBoothsUpdatePhoneBoothData = {
    id: string;
    requestBody: PhoneBoothCreate;
};

export type PhoneBoothsUpdatePhoneBoothResponse = (PhoneBoothRead);

export type PhoneBoothsDeletePhoneBoothData = {
    id: string;
};

export type PhoneBoothsDeletePhoneBoothResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RolesReadRolesResponse = (Array<RoleRead>);

export type RolesCreateRoleData = {
    requestBody: RoleCreate;
};

export type RolesCreateRoleResponse = (RoleRead);

export type RolesReadRoleData = {
    id: string;
};

export type RolesReadRoleResponse = (RoleRead);

export type RolesUpdateRoleData = {
    id: string;
    requestBody: RoleCreate;
};

export type RolesUpdateRoleResponse = (RoleRead);

export type RolesDeleteRoleData = {
    id: string;
};

export type RolesDeleteRoleResponse = (Message);

export type SensorEventsReadSensorEventsData = {
    limit?: number;
    skip?: number;
};

export type SensorEventsReadSensorEventsResponse = (Array<SensorEventRead>);

export type SensorEventsCreateSensorEventData = {
    requestBody: SensorEventCreate;
};

export type SensorEventsCreateSensorEventResponse = (SensorEventRead);

export type SensorEventsReadSensorEventData = {
    id: string;
};

export type SensorEventsReadSensorEventResponse = (SensorEventRead);

export type SensorEventsDeleteSensorEventData = {
    id: string;
};

export type SensorEventsDeleteSensorEventResponse = (Message);

export type SensorsReadSensorsResponse = (Array<SensorRead>);

export type SensorsCreateSensorData = {
    requestBody: SensorCreate;
};

export type SensorsCreateSensorResponse = (SensorRead);

export type SensorsReadSensorData = {
    id: string;
};

export type SensorsReadSensorResponse = (SensorRead);

export type SensorsUpdateSensorData = {
    id: string;
    requestBody: SensorCreate;
};

export type SensorsUpdateSensorResponse = (SensorRead);

export type SensorsDeleteSensorData = {
    id: string;
};

export type SensorsDeleteSensorResponse = (Message);

export type UsageSessionsReadUsageSessionsData = {
    limit?: number;
    skip?: number;
};

export type UsageSessionsReadUsageSessionsResponse = (Array<UsageSessionRead>);

export type UsageSessionsCreateUsageSessionData = {
    requestBody: UsageSessionCreate;
};

export type UsageSessionsCreateUsageSessionResponse = (UsageSessionRead);

export type UsageSessionsReadUsageSessionData = {
    id: string;
};

export type UsageSessionsReadUsageSessionResponse = (UsageSessionRead);

export type UsageSessionsDeleteUsageSessionData = {
    id: string;
};

export type UsageSessionsDeleteUsageSessionResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);